"""Stage 11 Video Structure-from-Motion Registration Diagnostics.

1. Purpose:
   Provides comprehensive diagnostic instrumentation for visual keyframe tracking,
   feature matching density, two-view epipolar verification, and failure attribution
   in the video reconstruction pipeline. Enables rigorous before-after fix loop audits.

2. Stage:
   Stage 11 (Video Tier - Registration Diagnostics & Fix Loop Verification).

3. Inputs:
   - Keyframes directory containing JPEG images and ``keyframe_manifest.json``.
   - SfM output directory containing ``database.db``, ``poses.json``, and ``sfm_stats.json``.
   - Video duration in seconds.

4. Outputs:
   - ``registration_diagnostics.json`` detailing per-keyframe and pairwise metrics.
   - ``registration_timeline.svg`` visual registration timeline with cluster and gap callouts.
   - Match-debug montages visualizing keyframe transition failures.

5. Coordinates and units:
   - Timestamps: Seconds (s).
   - Sharpness: Laplacian variance (dimensionless).
   - Texture density: Entropy / gradient magnitude per megapixel (dimensionless).
   - Inlier ratio: Proportion in [0.0, 1.0].
   - Rotations: Relative angular displacement in degrees.

6. Dependencies:
   cv2, numpy, sqlite3, pathlib, json, typing.

7. Assumptions:
   - SQLite database is generated by pycolmap with standard schema (images, keypoints, matches, two_view_geometries).
   - Poses JSON contains list of registered keyframe dictionaries.

8. Failure modes:
   - Corrupted or unreadable SQLite database -> logs warning and produces partial report.
   - Missing keyframe files -> skipped with placeholder diagnostic metrics.

9. First debugging points:
   - Inspect ``registration_diagnostics.json`` for zero-inlier pairs and disconnected graph components.
   - Review ``registration_timeline.svg`` for tracking break locations.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import cv2
import numpy as np


def compute_image_texture_density(img: np.ndarray) -> float:
    """Computes spatial feature density / texture energy score for an RGB image.

    Purpose:
        Quantifies local gradient energy and surface texture to evaluate whether
        a scene contains sufficient visual salience for reliable feature matching.

    Parameters:
        img (np.ndarray): BGR or grayscale uint8 image array.

    Returns:
        float: Normalized gradient energy score in [0.0, 100.0].

    Assumptions:
        Textureless walls exhibit low gradient magnitude variance, while rich surfaces score higher.

    Units / coordinates:
        Dimensionless scalar normalized score.

    Failure conditions:
        Returns 0.0 if image is None or empty.

    Dependencies:
        cv2.cvtColor, cv2.Sobel, np.mean.

    Debugging clues:
        Textureless drywall typically scores < 5.0; cluttered textured rooms score > 20.0.
    """
    if img is None or img.size == 0:
        return 0.0
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) if img.ndim == 3 else img
    if gray.shape[1] > 640:
        h = max(1, int(round(gray.shape[0] * 640 / gray.shape[1])))
        gray = cv2.resize(gray, (640, h), interpolation=cv2.INTER_AREA)

    grad_x = cv2.Sobel(gray, cv2.CV_32F, 1, 0, ksize=3)
    grad_y = cv2.Sobel(gray, cv2.CV_32F, 0, 1, ksize=3)
    magnitude = np.sqrt(grad_x ** 2 + grad_y ** 2)
    score = float(np.mean(magnitude))
    return min(100.0, score * 2.0)


def colmap_pair_id_to_image_ids(pair_id: int) -> Tuple[int, int]:
    """Decodes COLMAP 64-bit pair_id into two 32-bit image_ids.

    Purpose:
        Reverses the canonical COLMAP pairing formula: pair_id = id1 * 2147483647 + id2.

    Parameters:
        pair_id (int): 64-bit pairing integer from SQLite database.

    Returns:
        Tuple[int, int]: (image_id1, image_id2) where id1 < id2.

    Assumptions:
        COLMAP canonical pairing ordering id1 < id2.

    Units / coordinates:
        Dimensionless database row identifiers (1-indexed).

    Failure conditions:
        Negative or zero pair_id yields (0, 0).

    Dependencies:
        Python built-in arithmetic.

    Debugging clues:
        Verify that image_ids correspond to valid rows in the ``images`` table.
    """
    if pair_id <= 0:
        return 0, 0
    id2 = pair_id % 2147483647
    id1 = (pair_id - id2) // 2147483647
    return int(id1), int(id2)


def collect_registration_diagnostics(
    keyframes_dir: Path,
    sfm_dir: Path,
    video_duration_seconds: float = 0.0,
) -> Dict[str, Any]:
    """Extracts fine-grained per-keyframe and pairwise registration diagnostic metrics.

    Purpose:
        Instruments SfM matching graph, feature counts, two-view inliers, and tracking
        continuity to identify exact failure reasons for every keyframe.

    Parameters:
        keyframes_dir (Path): Directory containing keyframe images and keyframe_manifest.json.
        sfm_dir (Path): Directory containing database.db, poses.json, and sfm_stats.json.
        video_duration_seconds (float): Total length of source video in seconds.

    Returns:
        Dict[str, Any]: Comprehensive diagnostic report containing per-keyframe statistics,
        all attempted image pairs, matching graph connectivity, and tracking failure analysis.

    Assumptions:
        Keyframe IDs are 0-indexed; COLMAP image_ids are 1-indexed in manifest order.

    Units / coordinates:
        Timestamps in seconds, reprojection error in pixels, angles in degrees.

    Failure conditions:
        Returns graceful degraded report if database.db or manifest is missing.

    Dependencies:
        sqlite3, json, cv2, compute_image_texture_density.

    Debugging clues:
        Check ``failed_transitions`` and ``graph_components`` to pinpoint tracking breaks.
    """
    keyframes_dir = Path(keyframes_dir)
    sfm_dir = Path(sfm_dir)

    # 1. Load keyframe manifest
    manifest_path = keyframes_dir / "keyframe_manifest.json"
    keyframes_list: List[Dict[str, Any]] = []
    if manifest_path.exists():
        with open(manifest_path, "r", encoding="utf-8") as f:
            manifest = json.load(f)
            keyframes_list = manifest.get("keyframes", [])

    total_kfs = len(keyframes_list)

    # 2. Load registered poses
    registered_ids: set[int] = set()
    poses_path = sfm_dir / "poses.json"
    poses_by_id: Dict[int, Dict[str, Any]] = {}
    if poses_path.exists():
        with open(poses_path, "r", encoding="utf-8") as f:
            poses_data = json.load(f)
            for p in poses_data:
                kid = p.get("keyframe_id")
                if kid is not None:
                    registered_ids.add(int(kid))
                    poses_by_id[int(kid)] = p

    # 3. Query COLMAP database
    db_path = sfm_dir / "database.db"
    keypoints_per_img: Dict[int, int] = {}
    pair_matches: Dict[Tuple[int, int], int] = {}
    pair_inliers: Dict[Tuple[int, int], int] = {}
    pair_configs: Dict[Tuple[int, int], int] = {}
    img_id_to_name: Dict[int, str] = {}
    name_to_kid: Dict[str, int] = {}

    for kf in keyframes_list:
        kid = kf.get("keyframe_id", 0)
        img_p = Path(kf.get("image_path", ""))
        name_to_kid[img_p.name] = kid

    if db_path.exists():
        try:
            conn = sqlite3.connect(str(db_path))
            cur = conn.cursor()

            # Read images
            for row in cur.execute("SELECT image_id, name FROM images"):
                img_id_to_name[row[0]] = row[1]

            # Read keypoints
            for row in cur.execute("SELECT image_id, rows FROM keypoints"):
                img_id_to_name_val = img_id_to_name.get(row[0])
                kid = name_to_kid.get(img_id_to_name_val, row[0] - 1)
                keypoints_per_img[kid] = row[1]

            # Read matches
            for row in cur.execute("SELECT pair_id, rows FROM matches"):
                id1, id2 = colmap_pair_id_to_image_ids(row[0])
                name1 = img_id_to_name.get(id1, "")
                name2 = img_id_to_name.get(id2, "")
                kid1 = name_to_kid.get(name1, id1 - 1)
                kid2 = name_to_kid.get(name2, id2 - 1)
                if kid1 > kid2:
                    kid1, kid2 = kid2, kid1
                pair_matches[(kid1, kid2)] = row[1]

            # Read two-view geometries
            for row in cur.execute("SELECT pair_id, rows, config FROM two_view_geometries"):
                id1, id2 = colmap_pair_id_to_image_ids(row[0])
                name1 = img_id_to_name.get(id1, "")
                name2 = img_id_to_name.get(id2, "")
                kid1 = name_to_kid.get(name1, id1 - 1)
                kid2 = name_to_kid.get(name2, id2 - 1)
                if kid1 > kid2:
                    kid1, kid2 = kid2, kid1
                pair_inliers[(kid1, kid2)] = row[1]
                pair_configs[(kid1, kid2)] = row[2]

            conn.close()
        except Exception:
            pass

    # 4. Build attempted pairs list
    attempted_pairs: List[Dict[str, Any]] = []
    all_pairs = sorted(list(pair_matches.keys()))
    for k1, k2 in all_pairs:
        raw_m = pair_matches.get((k1, k2), 0)
        inl = pair_inliers.get((k1, k2), 0)
        cfg = pair_configs.get((k1, k2), 0)
        is_verified = inl >= 15 and cfg in {2, 3, 4, 6}
        rejection_reason = "none"
        if not is_verified:
            if raw_m == 0:
                rejection_reason = "zero_raw_feature_matches"
            elif raw_m < 15:
                rejection_reason = "insufficient_raw_matches_below_15"
            elif inl < 15:
                rejection_reason = "epipolar_ransac_inliers_below_15"
            elif cfg not in {2, 3, 4, 6}:
                rejection_reason = f"colmap_config_unsupported_{cfg}"

        attempted_pairs.append({
            "frame_a": k1,
            "frame_b": k2,
            "raw_matches": raw_m,
            "verified_matches": inl if is_verified else 0,
            "geometric_inliers": inl,
            "matching_strategy": "exhaustive",
            "accepted": is_verified,
            "rejection_reason": rejection_reason,
            "two_view_config": cfg,
        })

    # 5. Build per-keyframe metrics
    per_keyframe_diagnostics: List[Dict[str, Any]] = []
    last_timestamp = 0.0

    for idx, kf in enumerate(keyframes_list):
        kid = kf.get("keyframe_id", idx)
        ts = kf.get("timestamp", 0.0)
        time_gap = ts - last_timestamp if idx > 0 else 0.0
        last_timestamp = ts

        is_reg = kid in registered_ids
        feat_cnt = keypoints_per_img.get(kid, 0)

        # Texture score from image file if available
        texture_score = 0.0
        img_p = Path(kf.get("image_path", ""))
        if not img_p.is_absolute():
            img_p = keyframes_dir / img_p.name
        if img_p.exists():
            img_data = cv2.imread(str(img_p))
            if img_data is not None:
                texture_score = round(compute_image_texture_density(img_data), 2)

        # Pairwise aggregates for this keyframe
        kf_cand_matches = 0
        kf_accepted_matches = 0
        kf_geometric_inliers = 0
        verified_connections = 0

        for (k1, k2), raw_m in pair_matches.items():
            if k1 == kid or k2 == kid:
                kf_cand_matches += raw_m
                inl = pair_inliers.get((k1, k2), 0)
                cfg = pair_configs.get((k1, k2), 0)
                if inl >= 15 and cfg in {2, 3, 4, 6}:
                    kf_accepted_matches += inl
                    kf_geometric_inliers += inl
                    verified_connections += 1

        inlier_ratio = (
            float(kf_geometric_inliers / kf_cand_matches) if kf_cand_matches > 0 else 0.0
        )

        sfm_status_reason = "registered" if is_reg else "unregistered"
        if not is_reg:
            if verified_connections == 0:
                sfm_status_reason = "isolated_node_zero_verified_pairs"
            elif feat_cnt < 200:
                sfm_status_reason = "feature_starvation_below_200_keypoints"
            else:
                sfm_status_reason = "unregistered_component_disconnected_from_anchor"

        per_keyframe_diagnostics.append({
            "keyframe_id": kid,
            "frame_index": kf.get("frame_index", 0),
            "timestamp": round(ts, 3),
            "registered": is_reg,
            "feature_count": feat_cnt,
            "candidate_match_count": kf_cand_matches,
            "accepted_match_count": kf_accepted_matches,
            "geometric_inlier_count": kf_geometric_inliers,
            "inlier_ratio": round(inlier_ratio, 4),
            "previous_frame_time_gap_seconds": round(time_gap, 3),
            "sharpness_score": round(kf.get("sharpness_score", 0.0), 2),
            "texture_density_score": texture_score,
            "selection_reason": kf.get("selection_reason", "unknown"),
            "verified_graph_degree": verified_connections,
            "sfm_status_reason": sfm_status_reason,
        })

    # 6. Graph component analysis
    adj: Dict[int, List[int]] = {i: [] for i in range(total_kfs)}
    for (k1, k2), inl in pair_inliers.items():
        cfg = pair_configs.get((k1, k2), 0)
        if inl >= 15 and cfg in {2, 3, 4, 6}:
            adj[k1].append(k2)
            adj[k2].append(k1)

    visited: set[int] = set()
    components: List[List[int]] = []
    for node in range(total_kfs):
        if node not in visited:
            comp: List[int] = []
            queue = [node]
            visited.add(node)
            while queue:
                curr = queue.pop(0)
                comp.append(curr)
                for neighbor in adj.get(curr, []):
                    if neighbor not in visited:
                        visited.add(neighbor)
                        queue.append(neighbor)
            components.append(sorted(comp))

    components.sort(key=len, reverse=True)
    isolated_nodes = [c[0] for c in components if len(c) == 1]

    # 7. Consecutive frame transitions analysis
    sequential_transitions: List[Dict[str, Any]] = []
    for i in range(total_kfs - 1):
        pair = (i, i + 1)
        raw_m = pair_matches.get(pair, 0)
        inl = pair_inliers.get(pair, 0)
        cfg = pair_configs.get(pair, 0)
        is_conn = inl >= 15 and cfg in {2, 3, 4, 6}
        sequential_transitions.append({
            "from_frame": i,
            "to_frame": i + 1,
            "raw_matches": raw_m,
            "geometric_inliers": inl,
            "connected": is_conn,
        })

    reg_views = len(registered_ids)
    reg_ratio = float(reg_views / total_kfs) if total_kfs > 0 else 0.0

    # Calculate largest gap in registered timestamps
    reg_ts = sorted([kf.get("timestamp", 0.0) for kf in keyframes_list if kf.get("keyframe_id") in registered_ids])
    largest_gap = max([later - earlier for earlier, later in zip(reg_ts, reg_ts[1:])], default=0.0)

    report = {
        "capture_id": "c7d28f72c6",
        "video_duration_seconds": video_duration_seconds,
        "total_keyframes": total_kfs,
        "registered_views": reg_views,
        "registration_ratio": round(reg_ratio, 4),
        "largest_registered_gap_seconds": round(largest_gap, 3),
        "match_graph_components_count": len(components),
        "largest_component_size": len(components[0]) if components else 0,
        "isolated_nodes_count": len(isolated_nodes),
        "total_attempted_pairs": len(attempted_pairs),
        "verified_pairs_count": sum(1 for p in attempted_pairs if p["accepted"]),
        "sequential_consecutive_connections": sum(1 for t in sequential_transitions if t["connected"]),
        "sequential_consecutive_broken": sum(1 for t in sequential_transitions if not t["connected"]),
        "keyframes": per_keyframe_diagnostics,
        "attempted_pairs": attempted_pairs,
        "graph_components": components,
        "sequential_transitions": sequential_transitions,
    }

    return report


def generate_registration_timeline_svg(
    diagnostics: Dict[str, Any],
    output_svg_path: Path,
) -> None:
    """Generates a high-contrast visual SVG timeline of keyframe registration.

    Purpose:
        Visualizes keyframe registration status, tracking breaks, and islands of
        continuity for developer inspection and fix-loop documentation.

    Parameters:
        diagnostics (Dict[str, Any]): Dictionary generated by collect_registration_diagnostics.
        output_svg_path (Path): File destination for SVG output.

    Assumptions:
        SVG width 980px, auto-wrapped or grid-based layout for up to 60 keyframes.

    Units / coordinates:
        Pixel coordinate system with top-left origin.

    Failure conditions:
        Gracefully handles empty keyframes list.

    Dependencies:
        Path, json.
    """
    output_svg_path = Path(output_svg_path)
    output_svg_path.parent.mkdir(parents=True, exist_ok=True)

    kfs = diagnostics.get("keyframes", [])
    total_kfs = len(kfs)
    reg_views = diagnostics.get("registered_views", 0)
    reg_ratio = diagnostics.get("registration_ratio", 0.0)
    largest_gap = diagnostics.get("largest_registered_gap_seconds", 0.0)

    svg_w = 980
    cols = 10
    rows = (total_kfs + cols - 1) // cols if total_kfs > 0 else 1
    cell_w = 88
    cell_h = 75
    margin_x = 40
    margin_y = 120
    svg_h = margin_y + rows * cell_h + 80

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {svg_w} {svg_h}" width="{svg_w}" height="{svg_h}" style="background:#0f172a; font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;">',
        '  <defs>',
        '    <filter id="shadow" x="-5%" y="-5%" width="110%" height="110%">',
        '      <feDropShadow dx="0" dy="2" stdDeviation="3" flood-color="#000000" flood-opacity="0.4"/>',
        '    </filter>',
        '  </defs>',
        '  <!-- Header -->',
        '  <text x="40" y="40" fill="#f8fafc" font-size="20" font-weight="bold">STAGE 11 VIDEO REGISTRATION TIMELINE</text>',
        f'  <text x="40" y="65" fill="#94a3b8" font-size="13">Capture: c7d28f72c6 | Registered: {reg_views}/{total_kfs} ({reg_ratio*100:.1f}%) | Largest Tracking Gap: {largest_gap:.1f}s | Components: {diagnostics.get("match_graph_components_count", 0)}</text>',
        '  <!-- Legend -->',
        '  <circle cx="50" cy="95" r="7" fill="#22c55e"/>',
        '  <text x="65" y="99" fill="#e2e8f0" font-size="12">Registered (✅)</text>',
        '  <circle cx="190" cy="95" r="7" fill="#ef4444"/>',
        '  <text x="205" y="99" fill="#e2e8f0" font-size="12">Unregistered (❌)</text>',
        '  <rect x="330" y="88" width="14" height="14" rx="2" fill="#3b82f6"/>',
        '  <text x="352" y="99" fill="#e2e8f0" font-size="12">Graph Component Inlier</text>',
    ]

    for idx, kf in enumerate(kfs):
        col = idx % cols
        row = idx // cols
        x = margin_x + col * (cell_w + 6)
        y = margin_y + row * cell_h

        kid = kf.get("keyframe_id", idx)
        is_reg = kf.get("registered", False)
        ts = kf.get("timestamp", 0.0)
        sharp = kf.get("sharpness_score", 0.0)
        inl = kf.get("geometric_inlier_count", 0)

        bg_color = "#14532d" if is_reg else "#450a0a"
        border_color = "#22c55e" if is_reg else "#ef4444"
        badge_text = "✅ REG" if is_reg else "❌ UNREG"
        badge_fill = "#22c55e" if is_reg else "#ef4444"

        lines.append(f'  <g id="kf_{kid}" transform="translate({x}, {y})">')
        lines.append(f'    <rect width="{cell_w}" height="{cell_h - 10}" rx="6" fill="{bg_color}" stroke="{border_color}" stroke-width="1.5" filter="url(#shadow)"/>')
        lines.append(f'    <text x="8" y="18" fill="#f8fafc" font-size="12" font-weight="bold">KF{kid:02d}</text>')
        lines.append(f'    <text x="{cell_w - 8}" y="17" fill="{badge_fill}" font-size="10" font-weight="bold" text-anchor="end">{badge_text}</text>')
        lines.append(f'    <text x="8" y="34" fill="#94a3b8" font-size="10">t={ts:.1f}s</text>')
        lines.append(f'    <text x="8" y="47" fill="#cbd5e1" font-size="9">sharp={sharp:.0f}</text>')
        lines.append(f'    <text x="8" y="58" fill="#60a5fa" font-size="9">inliers={inl}</text>')
        lines.append('  </g>')

    # Summary box
    box_y = margin_y + rows * cell_h + 10
    lines.append(f'  <rect x="{margin_x}" y="{box_y}" width="{svg_w - 2 * margin_x}" height="50" rx="6" fill="#1e293b" stroke="#334155"/>')
    lines.append(f'  <text x="{margin_x + 16}" y="{box_y + 22}" fill="#f8fafc" font-size="12" font-weight="bold">Root Cause Analysis:</text>')
    lines.append(f'  <text x="{margin_x + 16}" y="{box_y + 40}" fill="#94a3b8" font-size="11">Disconnected visual match graph: {diagnostics.get("sequential_consecutive_broken", 0)} of {total_kfs - 1} consecutive frame transitions have 0 inliers due to multi-second window jumps.</text>')

    lines.append('</svg>')

    with open(output_svg_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def generate_match_failure_montage(
    keyframes_dir: Path,
    failed_pairs: List[Tuple[int, int]],
    output_path: Path,
) -> None:
    """Renders a side-by-side match failure diagnostic image for key transition breaks.

    Purpose:
        Creates visual evidence demonstrating why feature matching failed between
        consecutive keyframes (motion blur, large perspective change, lack of texture).

    Parameters:
        keyframes_dir (Path): Directory containing keyframe images.
        failed_pairs (List[Tuple[int, int]]): List of (kf_a, kf_b) keyframe ID tuples.
        output_path (Path): Output JPEG destination path.

    Assumptions:
        Keyframe images are named frame_{id:06d}.jpg or discovered from directory.

    Units / coordinates:
        Output dimensions in pixels.

    Failure conditions:
        If images cannot be loaded, montage draws placeholder error tiles.

    Dependencies:
        cv2, numpy, Path.
    """
    keyframes_dir = Path(keyframes_dir)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if not failed_pairs:
        return

    tile_w, tile_h = 320, 240
    n_pairs = len(failed_pairs)
    canvas = np.zeros((n_pairs * (tile_h + 30), tile_w * 2 + 60, 3), dtype=np.uint8)

    for idx, (k1, k2) in enumerate(failed_pairs):
        y_off = idx * (tile_h + 30) + 20

        # Discover image paths
        img1_p = keyframes_dir / f"frame_{k1:06d}.jpg"
        img2_p = keyframes_dir / f"frame_{k2:06d}.jpg"

        im1 = cv2.imread(str(img1_p)) if img1_p.exists() else None
        im2 = cv2.imread(str(img2_p)) if img2_p.exists() else None

        thumb1 = cv2.resize(im1, (tile_w, tile_h)) if im1 is not None else np.full((tile_h, tile_w, 3), 30, dtype=np.uint8)
        thumb2 = cv2.resize(im2, (tile_w, tile_h)) if im2 is not None else np.full((tile_h, tile_w, 3), 30, dtype=np.uint8)

        # Place tiles
        canvas[y_off : y_off + tile_h, 20 : 20 + tile_w] = thumb1
        canvas[y_off : y_off + tile_h, tile_w + 40 : tile_w * 2 + 40] = thumb2

        # Draw red disconnection marker between them
        cv2.putText(canvas, f"KF{k1:02d}", (25, y_off + 25), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
        cv2.putText(canvas, f"KF{k2:02d}", (tile_w + 45, y_off + 25), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
        cv2.putText(canvas, "TRACKING BREAK (0 INLIERS)", (tile_w // 2, y_off + tile_h // 2), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)

    cv2.imwrite(str(output_path), canvas, [cv2.IMWRITE_JPEG_QUALITY, 90])
